# Generated by Django 4.2.1 on 2023-06-14 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категорії'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статті'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публікація'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Час зміни'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категорія'),
        ),
    ]
